{
 "title": "Monitoring Dashboard - Mocha Madness Cafe",
 "description": "This dashboard will monitor the performance of Lambda functions ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "SQS Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQS - CSVTransformer Queue (Sent/Received/Deleted)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "dimensions": {
        "QueueName": "mocha-madness-CSVTransformer-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "NumberOfMessagesSent",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "eu-west-1",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-CSVTransformer-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "NumberOfMessagesReceived",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "eu-west-1",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-CSVTransformer-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "NumberOfMessagesDeleted",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "SQS - RedshiftLoader Queue (Sent/Received/Deleted)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
     "targets": [
      {
       "dimensions": {
        "QueueName": "mocha-madness-RedshiftLoader-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "NumberOfMessagesSent",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "eu-west-1",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-RedshiftLoader-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "NumberOfMessagesReceived",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "eu-west-1",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-RedshiftLoader-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "NumberOfMessagesDeleted",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "SQS - Dead Letter Queue (Message Available)",
     "type": "timeseries",
     "description": "The number of messages available for retrieval from the dead letter queue",
     "gridPos": { "h": 9, "w": 11, "x": 10, "y": 1 },
     "targets": [
      {
       "dimensions": {
        "QueueName": "mocha-madness-CSVTransformer-DLQ"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "ApproximateNumberOfMessagesVisible",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-RedshiftLoader-DLQ"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "ApproximateNumberOfMessagesVisible",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "SQS - Approximate Age Of Oldest Message",
     "type": "timeseries",
     "description": "After a message is received three times (or more) and not processed, the message is moved to the back of the queue and the ApproximateAgeOfOldestMessage metric points at the second-oldest message that hasn't been received more than three times.",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dimensions": {
        "QueueName": "mocha-madness-CSVTransformer-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "ApproximateAgeOfOldestMessage",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-RedshiftLoader-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "ApproximateAgeOfOldestMessage",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "SQS - Average Sent-Message Size",
     "type": "gauge",
     "description": "The size of messages added to a queue.",
     "gridPos": { "h": 9, "w": 11, "x": 10, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": {
        "QueueName": "mocha-madness-CSVTransformer-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "SentMessageSize",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "dimensions": {
        "QueueName": "mocha-madness-RedshiftLoader-queue"
       },
       "logGroups": [
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
         "name": "/aws/lambda/mocha-madness-CSVReader"
        },
        {
         "accountId": "015206308301",
         "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
         "name": "/aws/lambda/mocha-madness-CSVTransformer"
        }
       ],
       "metricName": "SentMessageSize",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  { "title": "Lambda Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Lambda - Invocations",
   "type": "timeseries",
   "description": "The number of times that your function code is invoked, including successful invocations and invocations that result in a function error. Invocations aren't recorded if the invocation request is throttled or otherwise results in an invocation error. The value of Invocations equals the number of requests billed.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "dimensions": { "FunctionName": "mocha-madness-CSVTransformer" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "mocha-madness-RedshiftLoader" },
     "logGroups": [
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
       "name": "/aws/lambda/mocha-madness-CSVReader"
      },
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
       "name": "/aws/lambda/mocha-madness-CSVTransformer"
      }
     ],
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda - Errors",
   "type": "timeseries",
   "description": "The number of invocations that result in a function error. Function errors include exceptions that your code throws and exceptions that the Lambda runtime throws. The runtime returns errors for issues such as timeouts and configuration errors. To calculate the error rate, divide the value of Errors by the value of Invocations. Note that the timestamp on an error metric reflects when the function was invoked, not when the error occurred.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "dimensions": { "FunctionName": "mocha-madness-CSVTransformer" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "mocha-madness-RedshiftLoader" },
     "logGroups": [
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
       "name": "/aws/lambda/mocha-madness-CSVReader"
      },
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
       "name": "/aws/lambda/mocha-madness-CSVTransformer"
      }
     ],
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda - Throttles",
   "type": "timeseries",
   "description": "The number of invocation requests that are throttled. When all function instances are processing requests and no concurrency is available to scale up, Lambda rejects additional requests with a TooManyRequestsException error. Throttled requests and other invocation errors don't count as either Invocations or Errors.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "mocha-madness-CSVTransformer" },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "mocha-madness-RedshiftLoader" },
     "logGroups": [
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
       "name": "/aws/lambda/mocha-madness-CSVReader"
      },
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
       "name": "/aws/lambda/mocha-madness-CSVTransformer"
      }
     ],
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda - Duration",
   "type": "timeseries",
   "description": " The amount of time that your function code spends processing an event. The billed duration for an invocation is the value of Duration rounded up to the nearest millisecond.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "mocha-madness-CSVTransformer" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "FunctionName": "mocha-madness-RedshiftLoader" },
     "logGroups": [
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVReader:*",
       "name": "/aws/lambda/mocha-madness-CSVReader"
      },
      {
       "accountId": "015206308301",
       "arn": "arn:aws:logs:eu-west-1:015206308301:log-group:/aws/lambda/mocha-madness-CSVTransformer:*",
       "name": "/aws/lambda/mocha-madness-CSVTransformer"
      }
     ],
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}